### ISSUE TITLE
Could not resolve host: git.sqcorp.co”

### ISSUE THREAD

**Issue by ThomasAtDiaverum** [AlecStrong/kotlin-native-cocoapods#16]
Hi, 

I followed your Setup. When I came to the Podfile I couldn’t resolve the source 'https://git.sqcorp.co/scm/ios/cocoapodspecs.git’.
I get the error message: 
`fatal: unable to access 'https://git.sqcorp.co/scm/ios/cocoapodspecs.git/': Could not resolve host: git.sqcorp.co`
Just `git clone https://git.sqcorp.co/scm/ios/cocoapodspecs.git` doesn’t work either. And I cannot resolve the source in my browser.
Maybe this is not a problem just in my end? Or am I doing something wrong?

Thanks in advance.

**Comment by AlecKazakova** [comment]
that part of the readme (the `Podfile`) wasn't meant to be copied over. I'll remove that bit from the readme. I recommend getting CocoaPods working before Kotlin/Native, it's a requirement for this project
