### ISSUE TITLE
Podspec script fails if user does not have realpath

### ISSUE THREAD

**Issue by einarvalgeirsson** [AlecStrong/kotlin-native-cocoapods#9]
I had an issue building my iOS project as the generated podspec file contained a shell script that used `realpath` which my Mac could not resolve. 
https://github.com/AlecStrong/kotlin-native-cocoapods/blob/master/gradle-plugin/src/main/kotlin/com/alecstrong/cocoapods/gradle/plugin/GeneratePodspecTask.kt#L57

I fixed this by installing CoreUtils (brew install coreutils). 

Perhaps this should be mentioned in the README?

**Comment by AlecKazakova** [comment]
we might just be able to remove `realpath` entirely. Thanks for the report!
